<a href="https://colab.research.google.com/github/javierraneros-cell/UD2-Mineria-de-Datos---Colab-/blob/main/Practica_UD2_ATLETAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# INTRODUCCIÓN

En esta actividad se va a trabajar con conjunto de datos que contiene las marcas de los alumnos de un centro de alto rendimiento en diferentes pruebas atléticas. Concretamente, los campos que se recogen son los siguientes:

grupo clase a la que pertenece cada alumno (A o B)

*   100m lisos: marca en la prueba de 100 metros lisos
*   400m lisos: marca en la prueba de 400 metros lisos
*   100m vallas: marca en la prueba de 100 metros vallas
*   1500m lisos: marca en la prueba de 1500 metros lisos
*   salto horizontal: marca en el salto de longitud
*   lanzamiento de peso: marca en lanzamiento de peso o de bala (bola de acero)
*   salto de altura: marca en el salto vertical de altura
*   disco: marca en lanzamiento de disco
*   pértiga: marca en salto con pértiga
*   jabalina: marca en lanzamiento de jabalina

El objetivo final es calcular una única medida que permita determinar el rendimiento de cada alumno. Como se tratan de diferentes pruebas medidas en diferentes unidades, resulta complicado encontrar la forma de resumir los resultados en un único valor numérico. Para esta tarea se va a utilizar el análisis de componentes principales que permite reducir el número de dimensiones manteniendo la mayor cantidad de información posible. Concretamente, se desea reducir el número de dimensiones a 1.

# PREPARACIÓN DE LOS DATOS

## Carga de los datos

Para esta tarea se facilitan 4 ficheros separadaos para cada atleta en las diferentes marcas descritas anteriormente y 2 días, por lo cual habrá que unir o concatenar los ficheros en un único Dataset.

Los 4 ficheros CSV se encuentran en el Drive al mismo nivel que el cuaderno Colab Notebook, por lo que se procede a su carga en la carpeta csv del proyecto:

In [1]:
# Instalar gdown si no está instalado
!pip install gdown

Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (5.2.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown) (3.25.2)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gdown) (4.67.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2026.2.25)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (1.7.1)

Para incorporar el fichero de Google Drive al proyecto hay que descargarlo con **gdown** y guaradarlos como ficheros CSV para despues ser usados en la creación del/los Datasets:

*   grupoA_primer_dia.csv 	--> 17qFwj7BbK7zcqDY_tIVkiqRQt7lIenD0
*   grupoA_segundo_dia.csv 	--> 1MZKjVE61nWtB8BbBz7xNFLPjrtK2ITmU
*   grupoB_primer_dia.csv		--> 1R6GKBa3KrlVtzPelqSXlqeEbD_33Trkd
*   grupoB_segundo_dia.csv	--> 1jvkkCQLWtOoHM3Pe2p0zwleyWeXLnpYG

In [2]:
import gdown

#IDs de los archivos a descargar de Google Drive que tienen que estar compartidos
# grupoA_primer_dia.csv 	--> 17qFwj7BbK7zcqDY_tIVkiqRQt7lIenD0
# grupoA_segundo_dia.csv 	--> 1MZKjVE61nWtB8BbBz7xNFLPjrtK2ITmU
# grupoB_primer_dia.csv		--> 1R6GKBa3KrlVtzPelqSXlqeEbD_33Trkd
# grupoB_segundo_dia.csv	--> 1ZFtBr0l30FKz7qyzaMMb6W74Lky6IDlv

file_grupoA_primer_dia_id = '17qFwj7BbK7zcqDY_tIVkiqRQt7lIenD0'
file_grupoA_segundo_dia_dia_id = '1MZKjVE61nWtB8BbBz7xNFLPjrtK2ITmU'
file_grupoB_primer_dia_id = '1R6GKBa3KrlVtzPelqSXlqeEbD_33Trkd'
file_grupoB_segundo_dia_id = '1ZFtBr0l30FKz7qyzaMMb6W74Lky6IDlv'

output_grupoA_primer_dia = 'grupoA_primer_dia.csv'
output_grupoA_segundo_dia = 'grupoA_segundo_dia.csv'
output_grupoB_primer_dia = 'grupoB_primer_dia.csv'
output_grupoB_segundo_dia = 'grupoB_segundo_dia.csv'

#GRUPO A
#Primer dia
url = f'https://drive.google.com/uc?id={file_grupoA_primer_dia_id}'
gdown.download(url, output_grupoA_primer_dia, quiet=False)
print('\nPrimer dia GRUPO A descargado...')
#Segundo dia
url = f'https://drive.google.com/uc?id={file_grupoA_segundo_dia_dia_id}'
gdown.download(url, output_grupoA_segundo_dia, quiet=False)
print('\nSegundo dia GRUPO A descargado...')
#GRUPO B
#Primer dia
url = f'https://drive.google.com/uc?id={file_grupoB_primer_dia_id}'
gdown.download(url, output_grupoB_primer_dia, quiet=False)
print('\nPrimer dia GRUPO B descargado...')
#Segundo dia
url = f'https://drive.google.com/uc?id={file_grupoB_segundo_dia_id}'
gdown.download(url, output_grupoB_segundo_dia, quiet=False)
print('\nSegundo dia GRUPO B descargado...')

Downloading...
From: https://drive.google.com/uc?id=17qFwj7BbK7zcqDY_tIVkiqRQt7lIenD0
To: /content/grupoA_primer_dia.csv
100%|██████████| 496/496 [00:00<00:00, 1.40MB/s]

Primer dia GRUPO A descargado...

Downloading...
From: https://drive.google.com/uc?id=1MZKjVE61nWtB8BbBz7xNFLPjrtK2ITmU
To: /content/grupoA_segundo_dia.csv
100%|██████████| 633/633 [00:00<00:00, 1.66MB/s]

Segundo dia GRUPO A descargado...

Downloading...
From: https://drive.google.com/uc?id=1R6GKBa3KrlVtzPelqSXlqeEbD_33Trkd
To: /content/grupoB_primer_dia.csv
100%|██████████| 1.02k/1.02k [00:00<00:00, 1.24MB/s]

Primer dia GRUPO B descargado...

Downloading...
From: https://drive.google.com/uc?id=1ZFtBr0l30FKz7qyzaMMb6W74Lky6IDlv
To: /content/grupoB_segundo_dia.csv
100%|██████████| 1.24k/1.24k [00:00<00:00, 4.27MB/s]

Segundo dia GRUPO B descargado...

## Creación Datasets

Tenemos que unir los 4 ficheros en una única fuente de datos. Para ello lo que vamos a hacer es crear 4 Datasets por cada ficheros csv y despues los concatenaremos.

In [3]:
import pandas as pd

#Creación de 4 Datasets y mostramos los datos
df_grupoA_primer_dia = pd.read_csv(output_grupoA_primer_dia)
print(f"Archivo '{output_grupoA_primer_dia}' descargado y cargado exitosamente.")
display(df_grupoA_primer_dia.head())

df_grupoA_segundo_dia = pd.read_csv(output_grupoA_segundo_dia)
print(f"\nArchivo '{output_grupoA_segundo_dia}' descargado y cargado exitosamente.")
display(df_grupoA_segundo_dia.head())

df_grupoB_primer_dia = pd.read_csv(output_grupoB_primer_dia)
print(f"\nArchivo '{output_grupoB_primer_dia}' descargado y cargado exitosamente.")
display(df_grupoB_primer_dia.head())

df_grupoB_segundo_dia = pd.read_csv(output_grupoB_segundo_dia)
print(f"\nArchivo '{output_grupoB_segundo_dia}' descargado y cargado exitosamente.")
display(df_grupoB_segundo_dia.head())

Archivo 'grupoA_primer_dia.csv' descargado y cargado exitosamente.

    alumno grupo  100m lisos  400m lisos  100m vallas  1500m lisos
0   Torres     A       11.04       49.81        14.69        291.7
1  Delgado     A       10.76       49.37        14.05        301.5
2  Ramírez     A       11.02       48.37        14.09        300.2
3     Díaz     A       11.02       48.93       -14.99        280.1
4  Sánchez     A       11.34       50.42        15.31        276.4

Archivo 'grupoA_segundo_dia.csv' descargado y cargado exitosamente.

,alumno,grupo,salto horizontal,lanzamiento de peso,salto de altura,disco,pértiga,jabalina
0,Torres,A,7.58,14.83,2.07,43.75,5.02,63.19
1,Delgado,A,7.40,14.26,1.86,50.72,4.92,60.15
2,Ramírez,A,7.30,14.77,2.04,48.95,4.92,50.31
3,Díaz,A,7.23,14.25,1.92,40.87,5.32,62.77
4,Sánchez,A,7.09,15.19,2.10,46.26,4.72,NaN

Archivo 'grupoB_primer_dia.csv' descargado y cargado exitosamente.

     alumno grupo  100m lisos  400m lisos  100m vallas  1500m lisos
0     Silva     B       10.85       48.36        14.05       280.01
1  González     B       10.44       49.19        14.13       282.00
2   Herrera     B       10.50       46.81        13.97       278.11
3    Guzmán     B       10.89       48.97        14.56       265.42
4      Ríos     B       10.62       47.97        14.01          NaN

Archivo 'grupoB_segundo_dia.csv' descargado y cargado exitosamente.

,alumno,grupo,salto horizontal,lanzamiento de peso,salto de altura,disco,pértiga,jabalina
0,Silva,B,7.84,16.36,2.12,48.72,5.0,70.52
1,González,B,7.96,15.23,2.06,50.11,4.9,69.71
2,Herrera,B,7.81,15.93,2.09,51.65,4.6,55.54
3,Guzmán,B,7.47,15.73,2.15,48.34,4.4,58.46
4,Ríos,B,7.74,14.48,1.97,43.73,4.9,55.39

## Integración de los datos CONCATENACION

La integración de los 4 Datasets se realizara con la concatenación se realizaría primero uniendo a los grupos A y B de cada dia con una concatenación por FILAS y despues concatenaremos por COLUMNAS para unir todos los registros del primer dia con todos los registros del segundo dia:


> **Concatenacion x FILAS**:
>
>     grupoA_primer_dia + grupoB_primer_dia   --> primer_dia
>
>     grupoA_segundo_dia + grupoB_segundo_dia --> segundo_dia

Para concatenar se usa el método **concat** de Pandas **axis=0** para concatenar por filas y **axis=1** para unir por columnas
```
# concat([dataset1, dataset2], axis= 0 )
```

> **Concatenacion x COLUMNAS**:
>
>     primer_dia +  segundo_dia

```
# concat([dataset1, dataset2], axis= 1 )
```

In [4]:
#Concatenación x FILAS - Dataset primer dia y Segundo dia
result_primer_dia = pd.concat([df_grupoA_primer_dia, df_grupoB_primer_dia], axis=0, ignore_index=True)
print(f"\nConcatenacion creada correctamente para result_primer_dia ...\n")
display(result_primer_dia.head())
display(result_primer_dia.tail())

result_segundo_dia = pd.concat([df_grupoA_segundo_dia, df_grupoB_segundo_dia], axis=0, ignore_index=True)
print(f"\nConcatenacion creada correctamente para result_segundo_dia ...\n")
display(result_segundo_dia.head())
display(result_segundo_dia.tail())

Concatenacion creada correctamente para result_primer_dia ...

    alumno grupo  100m lisos  400m lisos  100m vallas  1500m lisos
0   Torres     A       11.04       49.81        14.69        291.7
1  Delgado     A       10.76       49.37        14.05        301.5
2  Ramírez     A       11.02       48.37        14.09        300.2
3     Díaz     A       11.02       48.93       -14.99        280.1
4  Sánchez     A       11.34       50.42        15.31        276.4

      alumno grupo  100m lisos  400m lisos  100m vallas  1500m lisos
36  Figueroa     B       11.10       49.34        15.38       263.08
37   Aguilar     B       11.33       50.54        14.98       278.67
38    Montes     B       10.86       51.16        14.96       317.00
39   Morales     B       11.23       50.95        15.09       281.70
40   Jiménez     B       11.36       53.20        15.39       296.12

Concatenacion creada correctamente para result_segundo_dia ...

,alumno,grupo,salto horizontal,lanzamiento de peso,salto de altura,disco,pértiga,jabalina
0,Torres,A,7.58,14.83,2.07,43.75,5.02,63.19
1,Delgado,A,7.40,14.26,1.86,50.72,4.92,60.15
2,Ramírez,A,7.30,14.77,2.04,48.95,4.92,50.31
3,Díaz,A,7.23,14.25,1.92,40.87,5.32,62.77
4,Sánchez,A,7.09,15.19,2.10,46.26,4.72,NaN

,alumno,grupo,salto horizontal,lanzamiento de peso,salto de altura,disco,pértiga,jabalina
36,Figueroa,B,7.03,13.22,1.85,40.22,4.5,58.36
37,Aguilar,B,7.26,13.30,1.97,43.34,4.5,52.92
38,Montes,B,7.07,14.81,1.94,46.07,4.7,53.05
39,Morales,B,6.99,13.53,1.85,NaN,4.5,60.00
40,Jiménez,B,6.68,14.92,1.94,48.66,4.4,58.62

In [5]:
#Concatenacion x COLUMNAS
df_dataset = pd.concat([result_primer_dia, result_segundo_dia], axis=1)
print(f"\nConcatenacion creada correctamente para df_dataset ...\n")
display(df_dataset.head())
display(df_dataset.tail())

Concatenacion creada correctamente para df_dataset ...

,alumno,grupo,100m lisos,400m lisos,100m vallas,1500m lisos,alumno,grupo,salto horizontal,lanzamiento de peso,salto de altura,disco,pértiga,jabalina
0,Torres,A,11.04,49.81,14.69,291.7,Torres,A,7.58,14.83,2.07,43.75,5.02,63.19
1,Delgado,A,10.76,49.37,14.05,301.5,Delgado,A,7.40,14.26,1.86,50.72,4.92,60.15
2,Ramírez,A,11.02,48.37,14.09,300.2,Ramírez,A,7.30,14.77,2.04,48.95,4.92,50.31
3,Díaz,A,11.02,48.93,-14.99,280.1,Díaz,A,7.23,14.25,1.92,40.87,5.32,62.77
4,Sánchez,A,11.34,50.42,15.31,276.4,Sánchez,A,7.09,15.19,2.10,46.26,4.72,NaN

,alumno,grupo,100m lisos,400m lisos,100m vallas,1500m lisos,alumno,grupo,salto horizontal,lanzamiento de peso,salto de altura,disco,pértiga,jabalina
36,Figueroa,B,11.10,49.34,15.38,263.08,Figueroa,B,7.03,13.22,1.85,40.22,4.5,58.36
37,Aguilar,B,11.33,50.54,14.98,278.67,Aguilar,B,7.26,13.30,1.97,43.34,4.5,52.92
38,Montes,B,10.86,51.16,14.96,317.00,Montes,B,7.07,14.81,1.94,46.07,4.7,53.05
39,Morales,B,11.23,50.95,15.09,281.70,Morales,B,6.99,13.53,1.85,NaN,4.5,60.00
40,Jiménez,B,11.36,53.20,15.39,296.12,Jiménez,B,6.68,14.92,1.94,48.66,4.4,58.62

In [9]:
# Antes de eliminar, comprobamos que las posiciones 6 y 7 son de columnas duplicadas tras hacer la concatenación
print("Nombres de las columnas antes de eliminar:")
print(df_dataset.columns.tolist())

# Explicación del problema: df.drop() elimina todas las columnas con el nombre especificado.
# Para eliminar SOLO las columnas en las posiciones 6 y 7, seleccionaremos explícitamente las columnas que queremos mantener.

# Creamos una lista de índices de columnas que queremos mantener:
# Queremos mantener las columnas desde el índice 0 hasta el 5 (inclusive)
# y las columnas desde el índice 8 hasta el final.
columns_to_keep_indices = list(range(6)) + list(range(8, len(df_dataset.columns)))

# Seleccionar estas columnas para crear el nuevo DataFrame limpio,
# seleccionando con ILOC porque por nombre no podríamos referenciarlas al estar duplicadas:

df_dataset_cleaned = df_dataset.iloc[:, columns_to_keep_indices]

print("\nDataFrame después de eliminar las columnas duplicadas por índice:")
display(df_dataset_cleaned.head())
display(df_dataset_cleaned.tail())
print(f"El DataFrame ahora tiene {df_dataset_cleaned.shape[1]} columnas.")
print("Nombres de las columnas después de eliminar:")
print(df_dataset_cleaned.columns.tolist())

Nombres de las columnas antes de eliminar:
['alumno', 'grupo', '100m lisos', '400m lisos', '100m vallas', '1500m lisos', 'alumno', 'grupo', 'salto horizontal', 'lanzamiento de peso', 'salto de altura', 'disco', 'pértiga', 'jabalina']

DataFrame después de eliminar las columnas duplicadas por índice:

,alumno,grupo,100m lisos,400m lisos,100m vallas,1500m lisos,salto horizontal,lanzamiento de peso,salto de altura,disco,pértiga,jabalina
0,Torres,A,11.04,49.81,14.69,291.7,7.58,14.83,2.07,43.75,5.02,63.19
1,Delgado,A,10.76,49.37,14.05,301.5,7.40,14.26,1.86,50.72,4.92,60.15
2,Ramírez,A,11.02,48.37,14.09,300.2,7.30,14.77,2.04,48.95,4.92,50.31
3,Díaz,A,11.02,48.93,-14.99,280.1,7.23,14.25,1.92,40.87,5.32,62.77
4,Sánchez,A,11.34,50.42,15.31,276.4,7.09,15.19,2.10,46.26,4.72,NaN

,alumno,grupo,100m lisos,400m lisos,100m vallas,1500m lisos,salto horizontal,lanzamiento de peso,salto de altura,disco,pértiga,jabalina
36,Figueroa,B,11.10,49.34,15.38,263.08,7.03,13.22,1.85,40.22,4.5,58.36
37,Aguilar,B,11.33,50.54,14.98,278.67,7.26,13.30,1.97,43.34,4.5,52.92
38,Montes,B,10.86,51.16,14.96,317.00,7.07,14.81,1.94,46.07,4.7,53.05
39,Morales,B,11.23,50.95,15.09,281.70,6.99,13.53,1.85,NaN,4.5,60.00
40,Jiménez,B,11.36,53.20,15.39,296.12,6.68,14.92,1.94,48.66,4.4,58.62

El DataFrame ahora tiene 12 columnas.
Nombres de las columnas después de eliminar:
['alumno', 'grupo', '100m lisos', '400m lisos', '100m vallas', '1500m lisos', 'salto horizontal', 'lanzamiento de peso', 'salto de altura', 'disco', 'pértiga', 'jabalina']